name: Build and Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: gisul/sql-execution-engine:latest

    deploy:
        needs: build
        runs-on: self-hosted

        steps:
            - name: Deploy container
              run: |
                  docker pull gisul/sql-execution-engine:latest
                  docker rm -f sql-execution-engine 2>nul
                  docker run -d -p 6060:6060 --name sql-execution-engine --restart unless-stopped gisul/sql-execution-engine:latest
